In [6]:
!pip install pandas
!pip install scikit-learn
!pip install numpy

Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting scikit-learn
  Downloading scikit_learn-1.6.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Requirement already satisfied: numpy>=1.19.5 in /opt/conda/lib/python3.11/site-packages (from scikit-learn) (2.2.6)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.5 MB/s eta 0:00:00
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.5.1-py3-none-any.whl.metadata (5.6 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.6.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.5/13.5 MB 4.4 MB/s eta 0:00:0000:0100:01
Downloading joblib-1.5.1-py3-none-any.whl (307 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.7/307.7 kB 3.6 MB/s eta 0:00:0000:0100:01
Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 4.4 MB/s eta 0:00:0000:0100:01
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.5.1 scikit-learn-1.6.1 scipy-1.15.3 threadpoolctl-3.6.0
Requirement already satisfied: numpy in /opt/conda/lib/python3.11/site-packages (2.2.6)

In [7]:
import pandas as pd
import pickle
import os
import sklearn
import numpy

In [8]:
MODEL_PATH = "../shared/model.pkl"
TEST_PATH = "../shared/test.csv"
RESULT_PATH = "../shared/result.csv"

In [9]:
with open(MODEL_PATH, 'rb') as f:
    ct, model = pickle.load(f)
print(ct, model)

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['Hours Studied', 'Previous Scores',
                                  'Sleep Hours',
                                  'Sample Question Papers Practiced']),
                                ('cat', OneHotEncoder(),
                                 ['Extracurricular Activities'])]) LinearRegression()

In [13]:
test_df = pd.read_csv(TEST_PATH)
test_df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,Yes,9,1
1,8,51,Yes,7,2
2,8,91,No,4,5
3,5,79,No,7,8
4,2,72,No,4,3

In [15]:
X_data = ct.transform(test_df)
X_data

array([[ 0.78400258,  1.71388354,  1.46059403, -1.2629766 ,  0.        ,
         1.        ],
       [ 1.16872276, -1.07615504,  0.28269219, -0.91384884,  0.        ,
         1.        ],
       [ 1.16872276,  1.24887711, -1.48416055,  0.13353445,  1.        ,
         0.        ],
       ...,
       [-0.75487813, -1.36678406, -0.89520964,  1.18091773,  1.        ,
         0.        ],
       [ 1.55344294, -1.01802924,  1.46059403,  0.83178997,  1.        ,
         0.        ],
       [-1.52431848, -1.19240665, -1.48416055, -0.91384884,  0.        ,
         1.        ]], shape=(3000, 6))

In [16]:
feature_names = ct.get_feature_names_out()
X_trans = pd.DataFrame(X_data, columns=feature_names, index=test_df.index)

In [17]:
X_trans

,num__Hours Studied,num__Previous Scores,num__Sleep Hours,num__Sample Question Papers Practiced,cat__Extracurricular Activities_No,cat__Extracurricular Activities_Yes
0,0.784003,1.713884,1.460594,-1.262977,0.0,1.0
1,1.168723,-1.076155,0.282692,-0.913849,0.0,1.0
2,1.168723,1.248877,-1.484161,0.133534,1.0,0.0
3,0.014562,0.551367,0.282692,1.180918,1.0,0.0
4,-1.139598,0.144487,-1.484161,-0.564721,1.0,0.0
...,...,...,...,...,...,...
2995,1.168723,1.016374,-1.484161,1.530045,0.0,1.0
2996,-1.524318,-1.250532,0.871643,0.133534,0.0,1.0
2997,-0.754878,-1.366784,-0.895210,1.180918,1.0,0.0
2998,1.553443,-1.018029,1.460594,0.831790,1.0,0.0
2999,-1.524318,-1.192407,-1.484161,-0.913849,0.0,1.0

In [18]:
y_pred = model.predict(X_trans)
y_pred

array([91.83544022, 45.09158463, 84.33376137, ..., 25.32279018,
       50.28687918, 21.62339448], shape=(3000,))

In [19]:
result_df = pd.DataFrame(y_pred)
result_df.to_csv(RESULT_PATH, index=False)